### PR TITLE
rename event

### PR DESCRIPTION
**Pull request by evanillaa**

### CODE REVIEW

**Comment by evanillaa** [comment]
https://github.com/qbcore-framework/qb-radialmenu/pull/30/commits/e17257eaa33f52f8ec3a35de6664a411adc80420

**Comment by evanillaa** [comment]
https://github.com/qbcore-framework/qb-radialmenu/pull/30

**Review by Rhydium — APPROVED** [review]
LGTM

**Review by tomasalves8 — APPROVED** [review]

**Review by Eralpozcan — CHANGES_REQUESTED** [review]
Remove "AddEventHandler" for major update.

Change >  RegisterServerEvent to RegisterNetEvent
Look : qb-policejob server-side

Works for me this situtation.

**Pull request closed without merging**
